apiVersion: apps/v1
kind: Deployment
metadata:
  name: loganminaudo-website
  labels:
    app: loganminaudo-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loganminaudo-website
  template:
    metadata:
      labels:
        # Fixed the typo here (removed the extra 'd')
        app: loganminaudo-website
    spec:
      # Add this so K8s can pull from your Docker Hub if it's private
      imagePullSecrets:
        - name: dockerhub-conf
      containers:
        - name: loganminaudo-website
          image: loganminaudo/loganminaudo-website:0e0477bea4494d1b0f5d976db3b524afbd9be751
          # This tells K8s to always check for a new image even if the tag is the same
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"