apiVersion: v1
kind: Service
metadata:
  name: loganminaudo-website-service
spec:
  selector:
    app: loganminaudo-website
  ports:
    - protocol: TCP
      port: 80        # The port Traefik will talk to
      targetPort: 80  # The port inside your Docker container